run:
  name: run00_HPC_config_test
  notes: "Checking that the data for the whole temporal exten (glsea3) t goes through before moving to HPC"
  display_plots: save_only  # "auto", "show", or "save_only"

lake: superior

paths:
  output_root: ~/dev/deepsensor_projects/runs/

data_sources:
  sst:
    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/temporal/glsea_sst.zarr  # GLSEA (1996-2023)
#    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/temporal/glsea3_sst.zarr  # GLSEA3 (2007-current)
    format: zarr
    role: target
    use_anomalies: true
    sampling: random_lake_points
    variable: sst
    fill_values: []
  era5:
    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/temporal/greatlakes_era5_1995_2025.zarr
    format: zarr
    variables: [t2m_daily_mean]
    role: context
    sampling: all
    fill_values: []
#  ice_concentration:
#    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/temporal/ice_concentration.zarr
#    format: zarr
#    variable: ice_concentration
#    role: context
#    sampling: all
#    fill_values: []
  bathy:
    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/bathymetry/gl_bathy_depth_3arcsec_clean.nc
    format: netcdf
    variable: z
    role: [context, aux_at_targets]
    sampling: all
    coarsen_factor: 10
    fill_values: []
  lake_mask:
      path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/bathymetry/gl_landmask_3arcsec.nc
      format: netcdf
      variable: mask
      role: mask
      coarsen_factor: 25
      fill_values: []
#  dist_to_land:
#    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/bathymetry/gl_dist_to_land_3arcsec.nc
#    format: netcdf
#    variable: dist_to_land
#    role: [context, aux_at_targets]
#    coarsen_factor: 10
#    fill_values: []
#  core_depth:
#    path: /nfs/turbo/seas-dannes/SST-sensor-placement-input/pipeline_inputs/bathymetry/
#    format: netcdf
#    variable: core_depth
#    role: [context, aux_at_targets]
#    coarsen_factor: 10
#    fill_values: []

preprocessing:
  fit_range: ["2010-01-01", "2011-12-31"]  # This is the range of data that will be used to set up the dataprocessor for scaling the data
  force_reprocess: true

training:
  train_range: ["2009-01-01", "2012-12-31"] # The range of data exposed to the model for training
  val_range: ["2007-01-01", "2008-12-31"] # The range of data exposed for validation
  date_subsample_factor: 60
  n_epochs: 10
  lr: 5.0e-5
  patience: 15
  internal_density: 100
  n_context_points: 60
  vary_n_context: true
  min_n_context: 10
  max_n_context: 200


prediction:
  # Option 1: Specific dates
  dates: ["2021-03-15", "2021-06-01", "2021-07-15", "2021-10-01", "2022-03-15", "2022-06-01", "2022-07-15", "2022-10-01"]

  # Option 2: Random sample from val range
#  n_random: 10
#  seed: 42
#
#   Option 3: Every n days across val range
#  every_n_days: 30

  # Option 4: Override context points for prediction
#  every_n_days: 30
#  n_context: 50
