run:
  name: run00_local_config_test
  notes: "A run to see if this new env works with GL-TS and the new environemnt"
  display_plots: save_only  # "auto", "show", or "save_only"

lake: erie

paths:
  output_root: ~/dev/deepsensor_projects/runs/

data_sources:
  sst:
    path: /Users/jagraha/dev/deepsensor_projects/data/temporal_inputs/glsea3_sst.zarr
    format: zarr
    role: target
    use_anomalies: true
    sampling: random_lake_points
    variable: sst
    fill_values: []
  era5:
    path: /Users/jagraha/Data/ciglr_globus/greatlakes_era5_1995_2025.zarr
    format: zarr
    variables: [t2m_daily_mean, ssr_daily_sum, u10_daily_mean, v10_daily_mean]
    role: context
    sampling: all
    fill_values: []
#  ice_concentration:
#    path: /Users/jagraha/dev/deepsensor_projects/data/temporal_inputs/ice_concentration.zarr
#    format: zarr
#    variable: ice_concentration
#    role: context
#    sampling: all
#    fill_values: []
  bathy:
    path: ~/dev/deepsensor_projects/data/bathy/gl_bathy_depth_3arcsec_clean.nc
    format: netcdf
    variable: z
    role: [context, aux_at_targets]
    sampling: all
    coarsen_factor: 10
    fill_values: []
  lake_mask:
      path: ~/dev/deepsensor_projects/data/bathy/gl_landmask_3arcsec.nc
      format: netcdf
      variable: mask
      role: mask
      coarsen_factor: 25
      fill_values: []
#  dist_to_land:
#    path: ~/dev/deepsensor_projects/data/bathy/gl_dist_to_land_3arcsec.nc
#    format: netcdf
#    variable: dist_to_land
#    role: [context, aux_at_targets]
#    coarsen_factor: 10
#    fill_values: []
#  core_depth:
#    path: ~/dev/deepsensor_projects/data/bathy/gl_core_depth_3arcsec.nc
#    format: netcdf
#    variable: core_depth
#    role: [context, aux_at_targets]
#    coarsen_factor: 10
#    fill_values: []

preprocessing:
  fit_range: ["2017-01-01", "2019-12-31"]  # This is the range of data that will be used to set up the dataprocessor for scaling the data
  force_reprocess: false

training:
  train_range: ["2018-01-01", "2021-12-31"] # The range of data exposed to the model for training
  val_range: ["2022-01-01", "2023-12-31"] # The range of data exposed for validation
  date_subsample_factor: 60
  n_epochs: 10
  lr: 5.0e-5
  patience: 15
  internal_density: 50
  n_context_points: 60
  vary_n_context: true
  min_n_context: 10
  max_n_context: 200


prediction:
  # Option 1: Specific dates
  dates: ["2021-03-15", "2021-06-01", "2021-07-15", "2021-10-01", "2022-03-15", "2022-06-01", "2022-07-15", "2022-10-01"]

  # Option 2: Random sample from val range
#  n_random: 10
#  seed: 42
#
#   Option 3: Every n days across val range
#  every_n_days: 30

  # Option 4: Override context points for prediction
#  every_n_days: 30
#  n_context: 50
