run:
  name: run01_erie_fast_refactor_test
  notes: "erie_refactor_test"

lake: erie
environment: local

paths:
  output_root: ~/dev/deepsensor_projects/runs/erie_test/data_cache

data_sources:
  sst:
    path: ~/dev/deepsensor_projects/data/greatlakes_raw_temporal_ds_inputs/GLSEA_GCS_SST.zarr
    format: zarr
    role: target
    use_anomalies: true
    sampling: random_lake_points
    variable: sst
  era5:
    path: ~/dev/deepsensor_projects/data/greatlakes_raw_temporal_ds_inputs/era5_vars.zarr
    format: zarr
    variables: [t2m_daily_mean, ssr_daily_sum, u10_daily_mean, v10_daily_mean ]
    role: context
    sampling: all
  ice_concentration:
    path: ~/dev/deepsensor_projects/data/greatlakes_raw_temporal_ds_inputs/GL_Ice_Concentration_GCS.zarr
    format: zarr
    variable: ice_concentration
    role: context
    sampling: all
  bathy:
    path: ~/dev/deepsensor_projects/data/bathy/gl_bathy_depth_3arcsec_clean.nc
    format: netcdf
    variable: z
    role: [context, aux_at_targets]
    sampling: all
    coarsen_factor: 10
  lake_mask:
      path: ~/dev/deepsensor_projects/data/bathy/gl_landmask_3arcsec.nc
      format: netcdf
      variable: mask
      role: mask
      coarsen_factor: 25
#  dist_to_land:
#    path: ~/dev/deepsensor_projects/data/bathy/gl_dist_to_land_3arcsec.nc
#    format: netcdf
#    variable: dist_to_land
#    role: aux_at_targets
#    coarsen_factor: 10
#  core_depth:
#    path: ~/dev/deepsensor_projects/data/bathy/gl_core_depth_3arcsec.nc
#    format: netcdf
#    variable: core_depth
#    role: aux_at_targets
#    coarsen_factor: 10

preprocessing:
  fit_range: ["2018-01-01", "2018-12-31"]
  force_reprocess: false

training:
  train_range: ["2019-01-01", "2020-12-31"]
  val_range: ["2021-01-01", "2021-12-31"]
  date_subsample_factor: 5
  n_epochs: 25
  lr: 5.0e-5
  internal_density: 50
  n_context_points: 50
  vary_n_context: true
  min_n_context: 5
  max_n_context: 50
